const express = require('express')
const router = express.Router()
const {register, login, resetPassword, forgotPassword, updateTenantProfile} = require('../controllers/auth')
const {landlordRegister,contractList,landlordLogin, landlordForgotPassword, landlordResetPassword, updateProfile, getProfileInfo} = require('../controllers/LandlordAuth')
const { getContract, terminateContract } = require('../controllers/Tenant')
router.post('/register',register)
router.post('/login',login)
router.post('/landlordLogin',landlordLogin)
router.post('/landlordRegister',landlordRegister)
router.put('/updatetenantaccount/:id',updateTenantProfile)
router.put('/updateaccount/:id',updateProfile)
router.post('/forgotpassword',forgotPassword)
router.get('/getlandlord/:id',getProfileInfo)
router.get('/getcontract/:email',getContract)
router.get('/landlordgetcontract/:email',contractList)
router.delete('/terminatecontract/:email',terminateContract)
router.post('/landlordForgotPassword',landlordForgotPassword)
router.put('/passwordreset/:resetToken',resetPassword)
router.put('/landlordPasswordReset/:resetToken',landlordResetPassword)


module.exports = router